### ISSUE TITLE
Add super trait bound to proxy type

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#18]
I just noticed that I never thought about how this crate works with super traits. I guess that this:

```rust
trait Supi {}

#[auto_impl(Box, &)]
trait Foo: Supi {}
```

Should generate these impl blocks:

```rust
impl<T: Foo> Foo for Box<T>
where
    Box<T>: Supi,
{}

impl<'a, T: Foo> Foo for &'a T
where
    &'a T: Supi,
{}
```

Right? Or am I missing something? That logic should work for all proxy types, even `Fn`.

---
I can mentor anyone interested in tackling this issue :) 
Just ping me (via email, this issue, or in any other way)

**Instructions**: the important code for this issue is the function `header` in `gen.rs` (which, by the way, should be renamed to `gen_header`...). Here we generate everything outside of the braces `{}` of the impl block we are generating. What we need to do for this issue is basically "just" adding a bound to the `where` clause. Currently we use the `where_clause` variable as returned by `trait_def.generics.split_for_impl()`.

I think what we should do is generate our custom tokens for the where clause. This needs to be almost at the very end (just before the last `quote!` of the function). Here, we need to start with an token stream only holding `where`. Then we need to iterate through [the predicates](https://docs.rs/syn/0.14/syn/struct.WhereClause.html#structfield.predicates) adding each predicate to the token stream (and don't forget the comma!). Finally, we add our own predicate: `quote! { #self_ty: ??? }` where `???` should be a list of all super traits. 

A list of super traits can be obtained through [`trait_def.supertraits`](https://docs.rs/syn/0.14/syn/struct.ItemTrait.html#structfield.supertraits). It might be possible to simply use that field in the `quote!` macro. 

Finally, compile-pass tests should be added. (And mabye one `compile-fail` test where the super trait is not actually implemented for the proxy type).

If anything is unclear, just go ahead and ask!

**Comment by KodrAus** [comment]
Ah, good catch. Yeh, I think we should be able to add super trait bounds to all of the supported proxy types
