### ISSUE TITLE
Use impl header lifetime elision in generated impls for '&' and '&mut' once stable

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#22]
Just a reminder: once lifetime elision in impl headers (see [tracking issue](https://github.com/rust-lang/rust/issues/15872)) is stable, the generated code should use that feature. So instead of:

```rust
impl<'a, T> Foo for &'a T {}
```

It will be (at least I think that's the syntax):

```rust
impl<T> Foo for &T {}
```

Same for `&mut`.

This does matter as the generated code ends up in the docs. And we want that code to be as idiomatic as possible.

**Comment by scottmcm** [comment]
Yes, that's correct.  There's a bunch of examples from libcore in PR https://github.com/rust-lang/rust/pull/54687.

**Comment by LukasKalbertodt** [comment]
@scottmcm Thanks for creating the stabilization for 2015 PR <3 
Then, I can finally implement this issue.

**Comment by LukasKalbertodt** [comment]
As discussed in #44 implementing this is probably not really worth it. I will close this issue for now. If someone thinks this issue is absolutely worth solving, we can reopen.
