### ISSUE TITLE
`self` receiver and `FnMut`: cannot borrow immutable argument

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#23]
```rust
#[auto_impl(FnMut)]
trait FnTrait3 {
    fn execute(self);
}
```

Expands to:

```rust
impl<__AutoImplProxyT: ::std::ops::FnMut()> FnTrait3 for __AutoImplProxyT {
    fn execute(self) {
        self()
    }
}
```

Which errors because `self` is bound immutably but used mutably. To fix this, we could treat this as a special case and generate `(mut self)` instead of `(self)`. Maybe there is another way. Or we could simply always generate `({self})()` as body for Fn traits: the `{}` act as the identify function, so `self` can be used mutably or immutably. 

---
I can mentor anyone interested in tackling this issue :) 
Just ping me (via email, this issue, or in any other way)

**Instructions**: code generation of methods is done in `gen_method_item` in `gen.rs`. The important part for this issue is [here](https://github.com/KodrAus/auto_impl/blob/706b86a7aceef74af14bae5dca0302cb5b1204a5/src/gen.rs#L421-L423) (just search for `proxy_type.is_fn()`). The `quote!{ }` macro there is what generates code. Currently it's `quote! { self(#args) }` which is wrong. This probably just have to be changed as discussed above (the `{}` trick). Additionally, the compile test `value_self_for_fn_mut.rs` should be modified.

If anything is unclear, just go ahead and ask!

**Comment by KodrAus** [comment]
I like the `({self})()` trick here, since it means fewer special cases.
