### ISSUE TITLE
Emit warning on empty proxy type list

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#24]
The attribute `#[auto_impl()]` should lead to a warning on nightly. Sadly, we cannot emit warnings on stable (since the `proc_macro_diagnostic` API is still unstable).

---
I can mentor anyone interested in tackling this issue :) 
Just ping me (via email, this issue, or in any other way)

**Instructions**: Two things need to be done:
- First, we need to extend a few things in `diag.rs`. There, we have a few traits that abstract over nightly/stable diagnostic. Since, as said above, `proc_macro_diagnostic` is still unstable, we report errors on stable via a hack. Thus you'll find a few `#[cfg(feature = "nightly")]` attributes there. We need to add a `warn()` method to `SpanExt` first. With the nightly feature, we should simply return a `proc_macro::Diagnostic`. On stable... good question. We probably want to modify our own `Diagnostic` type so that it can also "be a warning". But if it's a warning, the `emit()` will just don't do anything.

- With that out of the way, we can finally tackle the core of this issue: emit the warning. I think the easiest way to do that is to add some code to `parse_types()` in `proxy.rs`. 

If anything is unclear, just go ahead and ask!

**Comment by felipehfs** [comment]
Hello, I'm a junior developer in Brazil and I want to contribute but I don't know how to get started.

**Comment by felipehfs** [comment]
My email is felipehfsouza@gmail.com if you want contact me.

**Comment by LukasKalbertodt** [comment]
@felipehfs Great! I wrote you a mail :)
