### ISSUE TITLE
Make `Fn*` types work with some generic methods 

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#37]
Currently, this:

```rust
#[auto_impl(Fn)]
trait Greeter {
    fn greet<T: Display>(&self, name: T);
}
```

Generates this:

```rust
impl<U: ::std::ops::Fn(T)> Greeter for U {
    fn greet<T: Display>(&self, name: T) {
        ({ self })(name)
    }
}
```

This doesn't compile as `T` is only declared on the method but already used in the impl header. We could make this specific thing work by moving `T: Display` to the impl header. 

But it's questionable whether we should support generic functions at all. `impl Trait` in argument position could be complicated. We would have to transform `impl Trait` generics into standard generics. If we would only support standard generics, that would... be kinda sad. 

Since we never claimed to support generics for `Fn*` types, I won't classify this as bug. But it would be nice to support in the future.

**Comment by KodrAus** [comment]
Could we use a similar technique to finding a reasonable name for generic types that we do with `find_suitable_param_names`?
