### ISSUE TITLE
Relicense as MIT/Apache-2

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#39]
I just noticed that this crate is currently licensed as MIT only. The vast majority of crates in the Rust eco-system are dual license as MIT/Apache-2. @KodrAus is there a specific reason you licensed it as only MIT? AFAIK, yes, MIT is strictly *more* liberal than Apache-2, but they are still somewhat incompatible and Apache-2 apparently helps with some trademark thingies? 

Anyway, I would immediately relicense everything I contributed as MIT/Apache-2. 

We should decide this ASAP before more contributors help out and make everything more complicated ^_^

**Comment by KodrAus** [comment]
@LukasKalbertodt There wasn't a special reason, adding Apache2 sounds good :+1:

Also cc @sarasend are you happy for your contributions to be licensed under dual MIT/Apache?

**Comment by KodrAus** [comment]
Also cc @saresend are you happy for your contributions to be licensed under dual MIT/Apache?

**Comment by saresend** [comment]
Yep, that works for me!

**Comment by LukasKalbertodt** [comment]
Perfect! Will create a PR once #38 is merged :)
