### ISSUE TITLE
Newtype support

### ISSUE THREAD

**Issue by RReverser** [auto-impl-rs/auto_impl#41]
It looks like this crate has all the needed machinery in place to be extended to work with any newtypes and not just smart pointers, allowing traits to opt-in to easily work with anything that implements `From<T> + Deref<Target = T>` (which all the smart pointers also already fit).

One approach could be to generate blanket implementation with trait bounds specified above, but another could be having an explicit internal wrapper which would be used by `#[auto_impl(newtype)]` on one side and by something like `#[derive(AutoImplNewtype)]` on another.

Either way, this could allow to solve the common issues with reimplementing traits for each newtype.

**Comment by RReverser** [comment]
I could play on a fork and make a PR if that helps?

**Comment by LukasKalbertodt** [comment]
Sure, if you already want to play with the code: go ahead. I thought about first discussing what we want, but already trying things out can help a lot! However, please don't invest a lot of time in implementing a solution you like without talking with us about that solution beforehand. Just in case we don't agree with the solution, we don't want you to waste your time :)

**Comment by RReverser** [comment]
Well in the worst case I can always go back to original plan and publish it as a separate crate later in case our views don't align. For now just trying to solve some specific cases I run into in myself all the time.

**Comment by KodrAus** [comment]
Coming back through some triage. In the intervening years the [`impl-tools`](https://github.com/kas-gui/impl-tools) project has sprung up which I think should support this use-case through its more programmatic `#[autoimpl]` syntax.

**Comment by RReverser** [comment]
Oh wow, it's been a while. I wonder what happened to that side-project and where I left it 😅

**Comment by KodrAus** [comment]
Come back to it 4 years later and close all the issues in the name of “triage”.
