### ISSUE TITLE
Add `!` (never) as proxy type

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#46]
I think this could be handy. It would just add an `impl Trait for ! {}`. This should work fine for all traits, that:
- don't have associated constants or types
- only have methods which take some sort of receiver (`self`, `&self` or `&mut self`).

All methods can then be implemented with `self` as body, because `!` is coercable to all other types. So we can basically implement the trait for `!` when we know that none of the trait items will ever be used :P

**Comment by KodrAus** [comment]
This sounds fair to me! I haven't been keeping up with the never type recently, but was there some talk about having it specially understood as always implementing all traits without bumping up against the usual coherence rules?

**Comment by LukasKalbertodt** [comment]
I'm also not sure tbh. I doubt that it will automatically be implemented for traits, as it shouldn't be implemented for some (e.g. `Default`). So... I'm not aware of those plans or any things that could make this issue impossible.

**Comment by KodrAus** [comment]
Coming back through some triage, this might be nice, but probably isn't something we're likely to add support for.
