### ISSUE TITLE
auto_impl for trait objects?

### ISSUE THREAD

**Issue by jsgf** [auto-impl-rs/auto_impl#49]
The use-case I run into most often is boilerplate for:
```
trait MyTrait {
...
}

impl MyTrait for Box<dyn MyTrait> {
// shim methods
}
```

Would it be possible to extend auto_impl to this case?

It would also need to support generating impls with autotraits/lifetimes:
```
impl MyTrait for Box<dyn MyTrait + Sync /* and/or 'static, Send, etc */> {
...
```

**Comment by LukasKalbertodt** [comment]
It would be absolutely possible to extend `auto_impl` for this use case! But at the same time, we should also support `&dyn Trait`, `&mut dyn Trait`, `Rc<dyn Trait>` and `Arc<dyn Trait>`. So basically every "pointer type" we currently support, only with a trait object.

I'm not quite sure how much work that would be. Hopefully we don't have to copy all the code for the other types, but can instead abstract somehow. Also the `Send`, `Sync` and lifetime bounds could be complicated. Mhhh...

I won't have time in the next months to implement this, but I could help you out if you want to try it!

**Comment by jsgf** [comment]
I had a poke around the source and came to similar conclusions. I was thinking of adding it as something like `#[auto_traitobj(&, Rc, Arc + Sync + 'static)]` - ie, basically the same syntax but with the ability to append marker traits.

As far as codegen goes, it would be nice to avoid duplicating all the existing code, but I haven't looked at it closely enough yet to work out how to do that.

**Comment by jsgf** [comment]
#52 addresses this more precisely.
