### ISSUE TITLE
Add proper compile-fail tests

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#55]
We already have compile-fail tests, but they in fact only check if compilation indeed fails. It does not check the error message at all. This is pretty unfortunate, because any other random failure can make the test pass. 

See [this PR](https://github.com/auto-impl-rs/auto_impl/pull/17) for discussion on how one would do that. We probably want to use a crate that does it for us, but it's not clear which one.

**Comment by CreepySkeleton** [comment]
You should take a look at [trybuild](https://github.com/dtolnay/trybuild) crate, it not only perform "compiles or not" check but also validates the error (actual/expected match).

**Comment by LukasKalbertodt** [comment]
@CreepySkeleton Oh wow that looks really good! dtolnay did it again! They are just incredible...

Anyway, thanks for mentioning that here! I looked for a good library that does this for quite some time! Will probably try at using it later.
