### ISSUE TITLE
Investigate using `syn-mid`

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#56]
I found [this project](https://github.com/taiki-e/syn-mid) which could help reduce compile times of `auto_impl`. Currently we use the "full" feature of `syn` which leads to a quite high compile time of that crate. `syn-mid` promises to solve that problem by not parsing function bodies. Sounds like we should use it for `auto_impl`. 

I didn't have time to investigate further, though. Hence this issue as a reminder.

**Comment by LukasKalbertodt** [comment]
`syn-mid` doesn't seem to offer `ItemTrait` and related types. So it seems like we can't use it here. 

@taiki-e: Hello there! Is there a reason why `syn-mid` does not offer `ItemTrait`? Or am I missing something? Do you think this project (`auto_impl`) could use `syn-mid`? We need to parse trait definitions, but we do not care about function bodies.

**Comment by taiki-e** [comment]
Hi @LukasKalbertodt. The types provided by `syn-mid` are not compatible with `visit` feature, so even if `syn-mid` provides `ItemTrait`, I think it is difficult to use `syn-mid` in `auto_impl `.

For example, the following visitor seems to be visiting the signature of a function, but [as `syn::Signature` needs `full` feature](https://github.com/dtolnay/syn/blob/40a51e96dddb47af7abceed2a78f3fa12a22cc00/src/item.rs#L1004), the same cannot be done with `syn-mid`.

https://github.com/auto-impl-rs/auto_impl/blob/f5d3f9bab4205be9f2a61bdde2faf949bbfd400d/src/analyze.rs#L46-L62

**Comment by LukasKalbertodt** [comment]
@taiki-e Thanks for checking out this issue and taking the time to have a look at this code! It's really appreciated.

The code you linked... could probably work fine without the `Visit` feature of `syn`, but would be more verbose. I guess we won't use `syn-mid` in `auto-impl` anytime soon then. We can revisit this issue if anything significant changes :)

Thanks again!
