### ISSUE TITLE
Auto-impl trait objects?

### ISSUE THREAD

**Issue by dpc** [auto-impl-rs/auto_impl#64]
```
impl Trait for Box<dyn Trait> { ... }
```

Any chance to support these?

**Comment by LukasKalbertodt** [comment]
I think this would be a useful addition to the library. However, won't have time to implement this any time soon. 

Also, there are some open questions, in particular how to specify those types in the `#[auto_impl(...)]` attribute. Maybe we should support `#[auto_impl(Box<dyn>)]` (trait object) and `#[auto_impl(Box<impl>)]` (the current behavior, static dispatc). And `#[auto_impl(Box)]` would just add both impl blocks? Just some quick ideas. I'd love to find a brief, easy to read and general syntax to specify impl blocks that `auto-impl` should generate. Ideas welcome!

**Comment by dpc** [comment]
I think `Box<dyn>` looks OK, and the previous ones can stay as they were.

Alternatively:

* `#[auto_impl(Box)]` does both `#[ auto_impl_dyn(Box)]` and  `#[auto_impl_stat(Box)]` do one or the other

**Comment by daniel5151** [comment]
I'd also love to see this added. It would let me remove [this gnarly macro](https://github.com/daniel5151/gdbstub/blob/784ba851c712a058b9e3850873ccb133709811ae/src/target/mod.rs#L322-L357) from my project :smile: 

Aside from `Box<dyn T>`, there's also `&dyn T` and `&mut dyn T` as well.

I would recommend keeping the two impls separate, as not all Traits can be used as Trait Objects (see [Object Safety](https://doc.rust-lang.org/book/ch17-02-trait-objects.html#object-safety-is-required-for-trait-objects)).

**Comment by KodrAus** [comment]
This might work best as an independent 'flag' somewhere in the attribute, since if you specify `#[auto_impl(&, Box)]` you probably want both to be implemented for `dyn Trait`. Maybe even just something like:

```rust
#[auto_impl(dyn, Box, &, &mut)]
pub trait Trait {}
```

So you don't have different items to bring into scope. It's a bit of a semantic overloading of what goes in the attribute, but I think it's a simple enough concept that it shouldn't be an issue. What do you think? I'm guessing _any_ support is going to be welcomed 😄

**Comment by daniel5151** [comment]
Seeing as #72 was just resolved, this is the only other issue that's blocking me from using `auto_impl` in [my project](https://github.com/daniel5151/gdbstub/blob/304c258409402309e5f3c7623d095b2e567c8d98/src/target/mod.rs#L479-L550).

Any updates on if/when this could get implemented?

**Comment by LukasKalbertodt** [comment]
@daniel5151 As you can see from this thread, there are a few open questions (mainly regarding how to specify this). To be honest, I don't use `auto_impl` anymore and have kind of lost interest in the project, so I will not implement this. If you want to see this, you probably have to implement it yourself :/ (and even then, no guarantees how quickly I can review the PR)

**Comment by dhardy** [comment]
FYI trait-objects are supported by [impl-tools](https://github.com/kas-gui/impl-tools/) (see [tests](https://github.com/kas-gui/impl-tools/blob/master/tests/autoimpl.rs#L111)) for examples).

**Comment by KodrAus** [comment]
This is probably something best left to `impl-tools` to handle. This library is quite tightly focused on a single simple use-case, so I've opened #79 to point users to it if they need something more sophisticated.
