### ISSUE TITLE
Use `Span::mixed_site`

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#69]
There is a new `Span` constructor in town. We could probably nicely use it in `auto_impl` and then probably remove the `nightly` feature completely.

**Comment by KodrAus** [comment]
Ah this is the more hygienic mode isn’t it? So we could avoid some if the fun old hacks for mangling names?

**Comment by LukasKalbertodt** [comment]
Yeah, though I would probably keep the "find a nice name" code, to make documentation nicer. Otherwise users might be confused by seeing `T` twice, referring to different things. *But* I am also not 100% sure how this mixed site works. I need to read up on that. This issue is as a reminder for me :P

**Comment by KodrAus** [comment]
Just coming back through some triage, this seems like it would be a nice bit of cleanup, but is unlikely to happen so I'll go ahead and close this one.
