### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by daniel5151** [auto-impl-rs/auto_impl#72]
At the moment, the generated code uses types prefixed with `::std::`. By switching to `::core::` and `alloc::`, `#[auto_impl]` could work with `no_std` projects as well.

- `std`'s `Arc`, `Rc`, and `Box` types are simply re-exports from [`alloc`](https://doc.rust-lang.org/alloc/).
- Skimming through the codebase, I noticed some other types which should be swapped out with their `::core` counterparts: e.g: `::std::ops::Fn` -> `::core::ops::Fn`, `::std::marker::Sized` -> `::core::marker::Sized`, etc...

**Comment by LukasKalbertodt** [comment]
Sounds like a good idea. Two things:

- Is it fine to unconditionally replace `::std::` with either `::alloc::` or `::core::`? Or would that break something and should this be behind a `no-std` crate feature? 
- Would this change bump the minimal required Rust version (currently 1.30)?

If you could look into those things, that'd be great!

**Comment by daniel5151** [comment]
The `::std` types are just [re-exports](https://doc.rust-lang.org/src/std/lib.rs.html#382) of the `::core`/`alloc` types, so this wouldn't break anything / require bumping the MSRV.
