### ISSUE TITLE
const generics support

### ISSUE THREAD

**Issue by skittles1412** [auto-impl-rs/auto_impl#84]
Consider the following code. It currently does not compile (on version 1.0.0).

```rs
#[auto_impl::auto_impl(&)]
trait Foo {
    fn foo<const I: i32>(&self);
}

fn main() {}
```

Using `cargo expand` I believe the macro expands to:
```rs
impl<'a, T: 'a + Foo + ?::core::marker::Sized> Foo for &'a T {
    fn foo<const I: i32>(&self) {
        T::foo(self)
    }
}
```

The `T::foo(self)` should be `T::foo::<I>(self)`

**Comment by KodrAus** [comment]
Thanks for the report @skittles1412!

We could probably just always list all generic bounds when expanding the `T::foo‘ call there, since that’s what we’d need to do if any const generics show up anyways.
