### ISSUE TITLE
request for crates.io minor release with syn 2 upgrade

### ISSUE THREAD

**Issue by audunhalland** [auto-impl-rs/auto_impl#94]
A new release including the [syn 2 PR](https://github.com/auto-impl-rs/auto_impl/pull/92) hasn't been published to crates.io, though [this comment](https://github.com/auto-impl-rs/auto_impl/pull/92#issuecomment-1594270420) said it would be.

Kindly requesting this as I'm looking to prune my various Cargo.locks. Thanks!

**Comment by KodrAus** [comment]
Thanks for the reminder @audunhalland! I'll take care of this now

**Comment by KodrAus** [comment]
This should be all done now :+1:

**Comment by audunhalland** [comment]
Thanks! `proc-macro-error` looks somewhat [unmaintained](https://gitlab.com/CreepySkeleton/proc-macro-error/-/merge_requests) though.

**Comment by KodrAus** [comment]
We probably don't need it anymore since `syn::Error` converts proc-macro errors into compile errors. I'm doing a little housekeeping on this library while I'm here so will roll that change in.
